version: "3.4"
services:
  mongo_1:
    image: mongo
    ports:
      - 27017:27017
    depends_on:
      - mongo_2
      - mongo_arbiter
    command:
      - --replSet
      - rs0
      - --bind_ip
      - localhost,mongo_1
  mongo_2:
    image: mongo
    command:
      - --replSet
      - rs0
      - --bind_ip
      - localhost,mongo_2
  mongo_arbiter:
    image: mongo
    command:
      - --replSet
      - rs0
      - --bind_ip
      - localhost,mongo_arbiter
